# Generated by Django 3.1.6 on 2021-02-23 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=120, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Вид энергоресурсов',
                'verbose_name_plural': 'Виды энергоресурсов',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя организации')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.adress', verbose_name='Адрес')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.organization', verbose_name='Организация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='MainAdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Главный адрес')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='website.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Главный адрес',
                'verbose_name_plural': 'Главные адреса',
            },
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.FloatField(default=0, verbose_name='Фактическое потребление')),
                ('limit', models.FloatField(default=0, verbose_name='Лимит потребления')),
                ('otklonenie', models.FloatField(editable=False, max_length=30)),
                ('otklonenie_percent', models.FloatField(editable=False, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.adress', verbose_name='Адрес')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='website.category', verbose_name='Категория услуги')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='website.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Отопление',
                'verbose_name_plural': 'Отопление',
            },
        ),
        migrations.AddField(
            model_name='adress',
            name='main_adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='website.mainadress', verbose_name='Главный адрес'),
        ),
        migrations.AddField(
            model_name='adress',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='website.organization', verbose_name='Организация'),
        ),
    ]
