# Generated by Django 3.1.6 on 2021-02-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsumingOtoplenie',
            new_name='Otoplenie',
        ),
        migrations.AlterModelOptions(
            name='adress',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='otoplenie',
            options={'verbose_name': 'Отопление', 'verbose_name_plural': 'Отопление'},
        ),
    ]
