# Generated by Django 3.1.6 on 2021-02-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otoplenie',
            name='otklonenie',
            field=models.FloatField(editable=False, max_length=30),
        ),
    ]
