# Generated by Django 3.1.6 on 2021-02-01 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210201_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='otoplenie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Опубликовано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otoplenie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='otoplenie',
            name='fact',
            field=models.FloatField(default=0, verbose_name='Фактическое потребление'),
        ),
        migrations.AlterField(
            model_name='otoplenie',
            name='limit',
            field=models.FloatField(default=0, verbose_name='Лимит потребления'),
        ),
    ]
