# Generated by Django 3.1.6 on 2021-04-23 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_consumption_main_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='main_adress',
        ),
    ]
