# Generated by Django 3.1.6 on 2021-02-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210211_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='otoplenie',
            name='otklonenie_percent',
            field=models.FloatField(default=0, editable=False, max_length=30),
        ),
    ]
