# Generated by Django 3.1.6 on 2021-04-23 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_consumption_main_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='main_adress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='website.mainadress', verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
