# Generated by Django 3.1.6 on 2021-02-02 05:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_otoplenie_organization'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='otoplenie',
            managers=[
                ('total', django.db.models.manager.Manager()),
            ],
        ),
    ]
