# Generated by Django 3.1.6 on 2021-02-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210202_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otoplenie',
            name='organization',
        ),
    ]
