# Generated by Django 3.1.6 on 2021-02-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210202_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otoplenie',
            name='fact_apr',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='fact_aug',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='fact_dec',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='fact_feb',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='fact_jan',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='fact_jul',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='fact_jun',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='fact_mar',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='fact_may',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='fact_nov',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='fact_oct',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='fact_sep',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='limit_apr',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='limit_aug',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='limit_dec',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='limit_feb',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='limit_jan',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='limit_jul',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='limit_jun',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='limit_mar',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='limit_may',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='limit_nov',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='limit_oct',
        ),
        migrations.RemoveField(
            model_name='otoplenie',
            name='limit_sep',
        ),
        migrations.AddField(
            model_name='otoplenie',
            name='fact',
            field=models.FloatField(default=0, verbose_name='Фактическое потребление'),
        ),
        migrations.AddField(
            model_name='otoplenie',
            name='limit',
            field=models.FloatField(default=0, verbose_name='Лимит потребления'),
        ),
    ]
