# Generated by Django 3.1.6 on 2021-02-11 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210202_1511'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='otoplenie',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='adress',
            name='organization',
        ),
        migrations.CreateModel(
            name='MainAdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Главный адрес')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='website.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Главный адрес',
                'verbose_name_plural': 'Главные адреса',
            },
        ),
        migrations.AddField(
            model_name='adress',
            name='main_adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='website.mainadress', verbose_name='Главный адрес'),
        ),
    ]
